---
- name: Check if NGINX is installed on all nodes
  hosts: all
  gather_facts: true

  tasks:

    - name: Check nginx package on Debian/Ubuntu
      ansible.builtin.shell: "dpkg -l | grep -w nginx"
      register: nginx_deb
      failed_when: false
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Check nginx package on RHEL/CentOS
      ansible.builtin.shell: "rpm -qa | grep -w nginx"
      register: nginx_rpm
      failed_when: false
      changed_when: false
      when: ansible_os_family == "RedHat"

    - name: Show result for Debian/Ubuntu
      debug:
        msg: "NGINX is {{ 'installed' if nginx_deb.stdout != '' else 'NOT installed' }}"
      when: ansible_os_family == "Debian"

    - name: Show result for RHEL/CentOS
      debug:
        msg: "NGINX is {{ 'installed' if nginx_rpm.stdout != '' else 'NOT installed' }}"
      when: ansible_os_family == "RedHat"
