---
- name: Ensure NGINX is installed
  hosts: all
  become: true
  gather_facts: true

  tasks:

    # -------- Debian / Ubuntu --------
    - name: Install nginx on Debian/Ubuntu
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    # -------- RHEL / CentOS --------
    - name: Install nginx on RHEL/CentOS
      ansible.builtin.yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"