---
- name: Remove NGINX and related packages
  hosts: all
  become: true
  gather_facts: true

  tasks:

    # -------- Debian / Ubuntu --------
    - name: Remove nginx on Debian/Ubuntu
      ansible.builtin.apt:
        name:
          - nginx
          - nginx-core
          - nginx-common
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"

    # -------- RHEL / CentOS --------
    - name: Remove nginx and related packages on RHEL/CentOS
      ansible.builtin.yum:
        name: "nginx*"
        state: absent
      when: ansible_os_family == "RedHat"