---
- name: Remove Nginx
  hosts: all
  become: yes
  tasks:
    - name: Ensure Nginx service is stopped
      ansible.builtin.service:
        name: nginx
        state: stopped
      when: ansible_facts['pkg_mgr'] in ['dnf', 'yum', 'apt']

    - name: Remove Nginx package on Red Hat-based systems
      ansible.builtin.package:
        name: nginx
        state: absent
      when: ansible_facts['os_family'] == "RedHat"

    - name: Remove Nginx package on Debian-based systems
      ansible.builtin.apt:
        name: nginx
        state: absent
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Debug OS Family
      debug:
        msg: "OS family is {{ ansible_facts['os_family'] }}, package manager is {{ ansible_facts['pkg_mgr'] }}"
